### ISSUE TITLE
Unknown keyword: :export-block when attempting export with org-tiddly-export-as-tiddly

### ISSUE THREAD

**Issue by l-de-lellis** [dfeich/org8-wikiexporters#3]
When attempting to export an org file to a tiddler with the command `org-tiddly-export-as-tiddly` I get the following error message:` Unknown keyword: :export-block`. I'm on org version 9.1.13 on emacs 26.1.

I get the same error when loading emacs: "`Error (use-package): ox-tiddly/:catch: Unknown keyword: :export-block`"

**Comment by dfeich** [comment]
The function for deriving a backend `org-export-define-derived-backend` no longer supports this older way to define export-blocks. I guess this changed when the export-block syntax changed. I did not catch it, because I am not using the Tiddly exporter any more (but still the Twiki one). I fixed it by simply removing this argument. Please try the new version.

**Comment by l-de-lellis** [comment]
Works fine. Thanks for the quick fix!
